name: BarTranslate

options:
  deploymentTarget:
    macOS: "12.6"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "2.2.0"
    CURRENT_PROJECT_VERSION: "2.2.0"
    SWIFT_VERSION: "5.0"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: G7QJ269WC7

configs:
  Debug: debug
  Release (GitHub): release
  Release (AppStore): release

packages:
  HotKey:
    url: https://github.com/soffes/HotKey
    exactVersion: 0.2.1

targets:
  BarTranslate:
    type: application
    platform: macOS
    deploymentTarget: "12.6"
    sources:
      - path: BarTranslate
        excludes:
          - Info.plist
          - .entitlements
          - ApplicationPopover.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ThijmenDam.BarTranslate
        CODE_SIGN_ENTITLEMENTS: BarTranslate/BarTranslate.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: BarTranslate
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.utilities"
        INFOPLIST_KEY_LSUIElement: YES
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        DEVELOPMENT_ASSET_PATHS: '"BarTranslate/Preview Content"'
        ENABLE_HARDENED_RUNTIME: YES
        ENABLE_PREVIEWS: YES
      configs:
        Release (AppStore):
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: APPSTORE
    dependencies:
      - package: HotKey
        product: HotKey

schemes:
  BarTranslate (Debug):
    build:
      targets:
        BarTranslate: all
    run:
      config: Debug
    archive:
      config: Debug
  BarTranslate (GitHub):
    build:
      targets:
        BarTranslate: all
    run:
      config: Release (GitHub)
    archive:
      config: Release (GitHub)
  BarTranslate (App Store):
    build:
      targets:
        BarTranslate: all
    run:
      config: Release (AppStore)
    archive:
      config: Release (AppStore)
