// tuple[0] is the key description
// tuple[1] is the key code

import { Modifier } from '../../../../../../electron/types';

export const keys = [
  ['a', 'KeyA'],
  ['b', 'KeyB'],
  ['c', 'KeyC'],
  ['d', 'KeyD'],
  ['e', 'KeyE'],
  ['f', 'KeyF'],
  ['g', 'KeyG'],
  ['h', 'KeyH'],
  ['i', 'KeyI'],
  ['j', 'KeyJ'],
  ['k', 'KeyK'],
  ['l', 'KeyL'],
  ['m', 'KeyM'],
  ['n', 'KeyN'],
  ['o', 'KeyO'],
  ['p', 'KeyP'],
  ['q', 'KeyQ'],
  ['r', 'KeyR'],
  ['s', 'KeyS'],
  ['t', 'KeyT'],
  ['u', 'KeyU'],
  ['v', 'KeyV'],
  ['w', 'KeyW'],
  ['x', 'KeyX'],
  ['y', 'KeyY'],
  ['z', 'KeyZ'],
  ['f1', 'F1'],
  ['f2', 'F2'],
  ['f3', 'F3'],
  ['f4', 'F4'],
  ['f5', 'F5'],
  ['f6', 'F6'],
  ['f7', 'F7'],
  ['f8', 'F8'],
  ['f9', 'F9'],
  ['f10', 'F10'],
  ['f11', 'F11'],
  ['f12', 'F12'],
  ['semi-colon', 'Semicolon'],
  ['equal sign', 'Equal'],
  ['comma', 'Comma'],
  ['dash', 'Minus'],
  ['period', 'Period'],
  ['forward slash', 'Slash'],
  ['backquote', 'Backquote'],
  ['open bracket', 'BracketLeft'],
  ['back slash', 'Backslash'],
  ['close bracket', 'BracketRight'],
  ['single quote', 'Quote'],
  ['0', 'Digit0'],
  ['1', 'Digit1'],
  ['2', 'Digit2'],
  ['3', 'Digit3'],
  ['4', 'Digit4'],
  ['5', 'Digit5'],
  ['6', 'Digit6'],
  ['7', 'Digit7'],
  ['8', 'Digit8'],
  ['9', 'Digit9'],
  ['numpad 0', 'Numpad0'],
  ['numpad 1', 'Numpad1'],
  ['numpad 2', 'Numpad2'],
  ['numpad 3', 'Numpad3'],
  ['numpad 4', 'Numpad4'],
  ['numpad 5', 'Numpad5'],
  ['numpad 6', 'Numpad6'],
  ['numpad 7', 'Numpad7'],
  ['numpad 8', 'Numpad8'],
  ['numpad 9', 'Numpad9'],
];

export const modifiers: [string, Modifier][] = [
  ['shift', 'shift'],
  ['ctrl', 'control'],
  ['alt/option', 'alt'],
  ['windows/command', 'meta'],
];

// export const modifiers = [
//   ['shift (left)', 'ShiftLeft '],
//   ['shift (right)', 'ShiftRight '],
//   ['ctrl (left)', 'ControlLeft '],
//   ['ctrl (right)', 'ControlRight '],
//   ['alt / option (left)', 'AltLeft '],
//   ['alt / option (right)', 'AltRight '],
//   ['windows / command (left)', 'MetaLeft '],
//   ['windows / command (right)', 'MetaRight '],
// ];
